version: '3.8'

services:
  api-backend:
    image: api-backend:latest
    networks:
      - app-network
    ports:
      - "5100:5100"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - REDIS_CONNECTION=redis:6379
      - RABBITMQ_HOSTNAME=rabbit
    depends_on:
      - redis
      - rabbit

  notification-service:
    image: notification-service:latest
    networks:
      - app-network
    ports:
      - "5104:5104"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - REDIS_CONNECTION=redis:6379
      - RABBITMQ_HOSTNAME=rabbit
    depends_on:
      - redis
      - rabbit

  frontend:
    image: frontend:latest
    networks:
      - app-network
    ports:
      - "4200:4200"
    depends_on:
      - api-backend

  redis:
    image: redis
    networks:
      - app-network
    ports:
      - "6379:6379"

  rabbit:
    image: rabbitmq:4.0-management
    networks:
      - app-network
    ports:
      - "5672:5672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

networks:
  app-network:
    driver: bridge 
