server {
	listen 80;
	server_name localhost;

	root /usr/share/nginx/html;
	index index.html;

	location / {
		try_files $uri $uri/ /index.html;
	}

	location /api/ {
		proxy_pass			http://api-backend:5100/api/;
		proxy_http_version	1.1;
		proxy_set_header	Upgrade $http_upgrade;
		proxy_set_header	Connection "upgrade";
		proxy_set_header	Host $host;
	}

	location /chatHub {
		proxy_pass			http://api-backend:5100/chatHub;
		proxy_http_version	1.1;
		proxy_set_header	Upgrade $http_upgrade;
		proxy_set_header	Connection "upgrade";
		proxy_set_header	Host $host;
	}

	location /userStatusHub {
		proxy_pass			http://api-backend:5100/userStatusHub;
		proxy_http_version	1.1;
		proxy_set_header	Upgrade $http_upgrade;
		proxy_set_header	Connection "upgrade";
		proxy_set_header	Host $host;
	}

	location /notificationsHub {
		proxy_pass			http://notification-service:5104/notificationsHub;
		proxy_http_version	1.1;
		proxy_set_header	Upgrade $http_upgrade;
		proxy_set_header	Connection "upgrade";
		proxy_set_header	Host $host;
	}
}
